version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq_DeliGo
    restart: 'no'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      - DeliGo_network

  postgres:
    image: postgres:17-alpine
    container_name: postgres_DeliGo
    restart: 'no'
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: deligo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d deligo"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - DeliGo_network
  
  pgadmin:
    container_name: pgadmin_DeliGo
    image: dpage/pgadmin4
    restart: 'no'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./.data/pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - DeliGo_network


networks:
  DeliGo_network:
    driver: bridge

volumes:
  data:
